Document: mingw-w64-termcap
Title: Debian mingw-w64-termcap Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-termcap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-termcap/mingw-w64-termcap.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-termcap/mingw-w64-termcap.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-termcap/mingw-w64-termcap.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-termcap/html/index.html
Files: /usr/share/doc/mingw-w64-termcap/html/*.html
